blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions / Community
    url: https://github.com/MuhammadLutfiMuzakiiVY
    about: Ask questions and discuss with the community.
  - name: Security Vulnerability Reporting
    url: https://github.com/MuhammadLutfiMuzakiiVY
    about: Privately report potential security vulnerabilities.
