name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Quality Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config
        
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cargo Cache
      uses: Swatinem/rust-cache@v2

    - name: Run Linter (Clippy)
      run: cargo clippy

    - name: Build Checks
      run: cargo check --verbose

    - name: Run Unit Tests
      run: cargo test --verbose
